#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# Helpers específicos deste wizard.
# ──────────────────────────────────────────────────────────────────────────

WRANGLER="npx wrangler"

# run_or_skip "descrição" comando...: pede confirmação, roda e registra o que
# ficou pendente se a pessoa pular ou o comando falhar.
run_or_skip() {
  local desc="$1"; shift
  if confirm "$desc agora?"; then
    if "$@"; then
      printf '  %s✓ ok%s %s\n' "$GREEN" "$RESET" "$desc"
    else
      SKIPPED+=("$desc (o comando falhou; rode de novo: $*)")
      warn "falhou: $desc"
    fi
  else
    SKIPPED+=("$desc (pulado: $*)")
    note "pulado."
  fi
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

if [[ ! -f wrangler.toml ]]; then
  printf '%sRode este wizard de dentro da pasta emailWorker/%s\n' "$RED" "$RESET"
  exit 1
fi
REPO_ROOT=$(cd .. && pwd)

banner "Aviso das publicações programadas em produção"

# ── Stage 1: chave da conta de serviço ──────────────────────────────────
stage "Chave da conta de serviço do Firebase"
say "O cron do Worker precisa de uma conta de serviço para ler a fila e gravar"
say "os avisos no banco de produção. Se você já tem a chave usada pelos scripts"
say "de manutenção (GOOGLE_APPLICATION_CREDENTIALS), ela serve e dá para pular a"
say "geração abaixo."
open_url "https://console.firebase.google.com/project/plataformacodefolio/settings/serviceaccounts/adminsdk"
step "Na aba 'Contas de serviço', com 'Firebase Admin SDK' selecionado,"
step "  clique em 'Gerar nova chave privada' e confirme."
step "Salve o arquivo JSON FORA do repositório, por exemplo em"
step "  ~/segredos/codefolio-sa.json. Nunca versione esse arquivo."
ask FIREBASE_SA_PATH "Caminho completo do JSON da conta de serviço:"
FIREBASE_SA_PATH="${FIREBASE_SA_PATH/#\~/$HOME}"
write_env FIREBASE_SA_PATH "$FIREBASE_SA_PATH"

# ── Stage 2: validar a chave ────────────────────────────────────────────
stage "Conferir a chave"
if [[ ! -f "$FIREBASE_SA_PATH" ]]; then
  printf '  %sArquivo não encontrado: %s%s\n' "$RED" "$FIREBASE_SA_PATH" "$RESET"
  exit 1
fi
SA_REAL=$(cd "$(dirname "$FIREBASE_SA_PATH")" && pwd)/$(basename "$FIREBASE_SA_PATH")
if [[ "$SA_REAL" == "$REPO_ROOT"/* ]]; then
  printf '  %sA chave está dentro do repositório (%s). Mova para fora e rode de novo.%s\n' \
    "$RED" "$SA_REAL" "$RESET"
  exit 1
fi
SA_EMAIL=$(node -e '
  const c = JSON.parse(require("fs").readFileSync(process.argv[1], "utf8"));
  if (!c.client_email || !c.private_key) process.exit(2);
  if (c.project_id && c.project_id !== "plataformacodefolio") process.exit(3);
  process.stdout.write(c.client_email);
' "$FIREBASE_SA_PATH") || {
  printf '  %sO arquivo não parece uma chave de conta de serviço do projeto plataformacodefolio%s\n' "$RED" "$RESET"
  printf '  %s(precisa ser JSON com client_email e private_key).%s\n' "$RED" "$RESET"
  exit 1
}
printf '  %s✓ ok%s chave de %s\n' "$GREEN" "$RESET" "$SA_EMAIL"
pause "Aperte Enter para continuar."

# ── Stage 3: segredo no Worker ──────────────────────────────────────────
stage "Cadastrar a chave como segredo do Worker"
say "A chave vai para o Cloudflare como o secret FIREBASE_SERVICE_ACCOUNT. O"
say "wrangler lê o arquivo direto, sem a chave passar pela tela."
note "Usa o token de API da Cloudflare (o mesmo do setup-wizard.sh). O login por"
note "navegador não funciona quando o segredo é enviado por pipe."
ask_secret CLOUDFLARE_API_TOKEN "Token de API da Cloudflare:"
export CLOUDFLARE_API_TOKEN
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
run_or_skip "Cadastrar FIREBASE_SERVICE_ACCOUNT no Worker" \
  bash -c "$WRANGLER secret put FIREBASE_SERVICE_ACCOUNT < \"\$0\"" "$FIREBASE_SA_PATH"
pause "Aperte Enter para continuar."

# ── Stage 4: regras do banco ────────────────────────────────────────────
stage "Publicar as regras do banco"
warn "Isto vai para PRODUÇÃO e precisa vir antes do app novo: sem a regra da"
warn "fila (publicationQueue), excluir quiz falha para todo mundo e o cron não"
warn "consegue consultar a fila por data."
note "Precisa do firebase CLI logado numa conta com acesso ao projeto"
note "(firebase login)."
run_or_skip "Publicar database.rules.json em produção" \
  bash -c "cd \"\$0\" && firebase deploy --only database --project plataformacodefolio" "$REPO_ROOT"
pause "Aperte Enter para continuar."

# ── Stage 5: preencher a fila ───────────────────────────────────────────
stage "Preencher a fila com o que já está programado"
say "Itens programados antes deste deploy não estão na fila e apareceriam sem"
say "aviso. Primeiro uma simulação, que só lista o que falta:"
(cd "$REPO_ROOT" && GOOGLE_APPLICATION_CREDENTIALS="$FIREBASE_SA_PATH" \
  node scripts/backfillPublicationQueue.mjs) || warn "a simulação falhou; veja a mensagem acima."
run_or_skip "Gravar essas entradas na fila de produção" \
  bash -c "cd \"\$0\" && GOOGLE_APPLICATION_CREDENTIALS=\"\$1\" node scripts/backfillPublicationQueue.mjs --apply" \
  "$REPO_ROOT" "$FIREBASE_SA_PATH"
pause "Aperte Enter para continuar."

# ── Stage 6: publicar o Worker ──────────────────────────────────────────
stage "Publicar o Worker"
say "Publica o Worker com o cron de 5 em 5 minutos. A partir daqui, cada"
say "publicação programada que vencer avisa a turma: sino para vídeo e slide,"
say "sino e e-mail para quiz."
run_or_skip "Publicar o Worker (wrangler deploy)" $WRANGLER deploy
pause "Aperte Enter para continuar."

# ── Stage 7: conferir ───────────────────────────────────────────────────
stage "Conferir o cron no ar"
say "O cron roda nos minutos múltiplos de 5. No log, procure a linha"
step "'Publicações programadas: {...}': está funcionando;"
step "'sem conta de serviço': o secret FIREBASE_SERVICE_ACCOUNT não chegou;"
step "'Token do Google recusado': a chave foi revogada ou é de outro projeto."
note "O log fica aberto até você apertar Ctrl-C."
if confirm "Abrir o log do Worker (wrangler tail) agora?"; then
  $WRANGLER tail || true
fi

finish
