#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# Helpers specific to this wizard (wrangler.toml editing, CLI wrapper).
# ──────────────────────────────────────────────────────────────────────────

# set_toml_value KEY VALUE: replaces `KEY = "..."` in wrangler.toml in place.
# Portable sed -i (GNU/BSD both accept the .bak suffix form).
set_toml_value() {
  local key="$1" value="$2"
  sed -i.bak -E "s#^${key} = \".*\"#${key} = \"${value}\"#" wrangler.toml
  rm -f wrangler.toml.bak
  printf '  %s✓ wrote%s %s → wrangler.toml\n' "$GREEN" "$RESET" "$key"
}

WRANGLER="npx wrangler"

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

if [[ ! -f wrangler.toml ]]; then
  printf '%sRode este wizard de dentro da pasta emailWorker/%s\n' "$RED" "$RESET"
  exit 1
fi

banner "Fila de e-mail: Cloudflare Workers + Queues + Brevo"

# ── Stage 1: conta Cloudflare + token de API ────────────────────────────
stage "Conta Cloudflare e token de API"
say "O Worker roda na Cloudflare. Se você ainda não tem conta, crie uma agora"
say "(o plano free já cobre tudo que este setup usa: Workers, Queues e KV)."
open_url "https://dash.cloudflare.com/sign-up"
pause "Depois de ter (ou já tendo) uma conta, aperte Enter para continuar."
say "Usamos um token de API em vez de 'wrangler login': o login por OAuth do"
say "navegador não sobrevive ao passo que envia o segredo do Brevo por pipe"
say "(stage 4), então o wrangler passa a exigir um token mesmo assim."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Clique em 'Create Token'."
step "Use o template 'Edit Cloudflare Workers' (cobre Workers Scripts e KV)."
step "Se der erro de permissão ao criar a fila no deploy (stage 6), volte aqui"
step "  e adicione a permissão 'Workers Queues: Edit' num token customizado."
step "Continue, revise e clique em 'Create Token' — copie o valor (só aparece"
step "  uma vez)."
ask_secret CLOUDFLARE_API_TOKEN "Token de API da Cloudflare:"
export CLOUDFLARE_API_TOKEN
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
if $WRANGLER whoami >/dev/null 2>&1; then
  printf '  %s✓ ok%s token válido.\n' "$GREEN" "$RESET"
else
  warn "não consegui validar o token com 'wrangler whoami' — confira se copiou"
  warn "certo. Vou seguir mesmo assim; se os próximos passos falharem, rode o"
  warn "wizard de novo com o token correto."
fi

# ── Stage 2: instalar dependências ──────────────────────────────────────
stage "Instalar dependências do worker"
say "Instalando wrangler e jose (verificação do token do Firebase) via npm."
npm install
say "Dependências instaladas."

# ── Stage 3: Firebase Project ID ────────────────────────────────────────
stage "Firebase Project ID"
say "O Worker usa isso para validar o token de login do app (garante que só"
say "usuários autenticados no CodeFolio conseguem enfileirar e-mail)."
FIREBASE_PROJECT_ID=""
if [[ -f ../.env ]]; then
  guess=$(grep -E '^VITE_PROJECT_ID=' ../.env | tail -n1 | cut -d= -f2- || true)
fi
if [[ -n "${guess:-}" ]]; then
  note "encontrado em ../.env (VITE_PROJECT_ID): $guess — é o mesmo Project ID do Firebase."
  if confirm "Usar esse valor?"; then
    FIREBASE_PROJECT_ID="$guess"
  fi
fi
if [[ -z "$FIREBASE_PROJECT_ID" ]]; then
  open_url "https://console.firebase.google.com/"
  step "Abra o projeto do CodeFolio → ⚙️ Configurações do projeto → aba Geral."
  step "Copie o valor de 'ID do projeto'."
  ask FIREBASE_PROJECT_ID "Project ID:"
fi
set_toml_value "FIREBASE_PROJECT_ID" "$FIREBASE_PROJECT_ID"
write_env FIREBASE_PROJECT_ID "$FIREBASE_PROJECT_ID"

# ── Stage 4: Brevo — remetente verificado + API key ─────────────────────
stage "Brevo: remetente verificado e API key"
say "Free do Brevo: 300 e-mails/dia. Precisamos de um remetente verificado e"
say "de uma API key transacional."
open_url "https://app.brevo.com/"
step "Crie a conta Brevo, se ainda não tiver (Sign up free)."
step "Vá em Settings → Senders, Domains & Dedicated IPs → Senders."
step "Adicione e verifique o e-mail que vai aparecer como remetente (você"
step "  recebe um e-mail de confirmação nesse endereço)."
ask BREVO_SENDER_EMAIL "E-mail do remetente verificado:"
set_toml_value "BREVO_SENDER_EMAIL" "$BREVO_SENDER_EMAIL"
write_env BREVO_SENDER_EMAIL "$BREVO_SENDER_EMAIL"

open_url "https://app.brevo.com/settings/keys/api"
step "Clique em 'Generate a new API key', dê um nome (ex: codefolio-worker)"
step "  e copie a chave (só aparece uma vez)."
ask_secret BREVO_API_KEY "API key do Brevo:"
printf '%s' "$BREVO_API_KEY" | $WRANGLER secret put BREVO_API_KEY
printf '  %s✓ definido%s BREVO_API_KEY como secret do Worker (Cloudflare)\n' "$GREEN" "$RESET"

# ── Stage 5: KV namespace para o contador diário ─────────────────────────
stage "KV namespace (contador diário de e-mails)"
existing_id=$(grep -A2 '\[\[kv_namespaces\]\]' wrangler.toml | grep -E '^id = "' | sed -E 's/^id = "(.*)"$/\1/' || true)
if [[ -n "$existing_id" ]]; then
  note "wrangler.toml já tem um KV namespace configurado (id: $existing_id) — provavelmente já é o certo, de um deploy anterior."
  if confirm "Ignorar e recriar do zero mesmo assim? (raramente é o que você quer — apaga o contador atual)"; then
    sed -i.bak '/^\[\[kv_namespaces\]\]$/,/^id = /d' wrangler.toml
    rm -f wrangler.toml.bak
    existing_id=""
  else
    note "mantendo o KV namespace existente."
  fi
fi
if [[ -z "$existing_id" ]]; then
  say "Criando o KV namespace EMAIL_META (guarda quantos e-mails já saíram hoje)."
  kv_output=$($WRANGLER kv namespace create EMAIL_META 2>&1) || {
    printf '%s\n' "$kv_output"
    warn "não consegui criar o KV namespace — veja a saída acima e rode de novo."
    exit 1
  }
  printf '%s\n' "$kv_output"
  kv_id=$(printf '%s' "$kv_output" | grep -oE 'id = "[a-f0-9-]+"' | head -n1 | sed -E 's/id = "(.*)"/\1/' || true)
  if [[ -z "$kv_id" ]]; then
    warn "não consegui extrair o id automaticamente da saída acima."
    ask KV_NAMESPACE_ID "Cole aqui o id que apareceu:"
    kv_id="$KV_NAMESPACE_ID"
  fi
  # wrangler rejeita id vazio na validação do config, então o bloco só é
  # escrito no wrangler.toml agora que existe um id real.
  {
    printf '\n[[kv_namespaces]]\n'
    printf 'binding = "EMAIL_META"\n'
    printf 'id = "%s"\n' "$kv_id"
  } >> wrangler.toml
  printf '  %s✓ wrote%s [[kv_namespaces]] (id = %s) → wrangler.toml\n' "$GREEN" "$RESET" "$kv_id"
fi

# ── Stage 6: deploy e teste de fumaça ────────────────────────────────────
stage "Deploy e teste"
say "Antes do primeiro deploy, sua conta Cloudflare precisa de um subdomínio"
say "workers.dev registrado (gratuito, é só escolher um nome único uma vez)."
open_url "https://dash.cloudflare.com/"
step "Entre na conta → Workers & Pages → Overview."
step "Se aparecer um convite para escolher um subdomínio workers.dev, escolha"
step "  um nome e confirme. Se já tiver um registrado, pode seguir direto."
pause "Depois de garantir o subdomínio, aperte Enter para publicar o Worker."

say "Publicando o Worker."
deploy_output=$($WRANGLER deploy 2>&1) || {
  printf '%s\n' "$deploy_output"
  warn "o deploy falhou — veja a saída acima."
  exit 1
}
printf '%s\n' "$deploy_output"
worker_url=$(printf '%s' "$deploy_output" | grep -oE 'https://[a-zA-Z0-9.-]+\.workers\.dev' | head -n1 || true)
if [[ -z "$worker_url" ]]; then
  ask WORKER_URL "Não achei a URL automaticamente — cole aqui a URL do Worker (https://...workers.dev):"
  worker_url="$WORKER_URL"
fi
say "Testando /enqueue sem token (deve responder 401 Unauthorized)."
status=$(curl -s -o /dev/null -w '%{http_code}' -X POST "${worker_url}/enqueue" || true)
if [[ "$status" == "401" ]]; then
  printf '  %s✓ ok%s /enqueue respondeu 401 como esperado (protegido).\n' "$GREEN" "$RESET"
else
  warn "/enqueue respondeu $status (esperava 401) — confira os logs com 'npx wrangler tail'."
fi

# A URL mora só no .env do app (como VITE_EMAIL_WORKER_URL), que é quem
# precisa dela em tempo de build. Guardar uma cópia aqui só criaria duas
# fontes da verdade para o mesmo valor.
prev_env_file="$ENV_FILE"
ENV_FILE="../.env"
write_env VITE_EMAIL_WORKER_URL "$worker_url"
ENV_FILE="$prev_env_file"
note "VITE_EMAIL_WORKER_URL gravado no .env do app — é de lá que o front lê."

finish
say "Worker publicado em: $worker_url"
say "Próximo passo (fora deste wizard): trocar sendNotificationEmailJS por uma"
say "chamada a este endpoint em src/api/services/emailService.js."
